# Attempt at a custom Azure-pipelines CI/CD pipeline definition. This is a YAML file which
# defines the stages/jobs/steps to take as part of the pipeline; basically like the Jenkinsfile
# one would use if they were using Jenkins!

# Reference
# #########
# YAML Schema:      https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops 
# Built-in 'tasks': https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/?view=azure-devops
# Quickstart guide: https://docs.microsoft.com/en-us/azure/devops/pipelines/customize-pipeline?view=azure-devops


# Specifies the name formatting for this pipeline as a whole. I.e., the formatting of the name for each
# 'run' of this pipeline.
name: $(Date:yyyyMMdd)$(Rev:.r)

# Specify any pipeline-level variables to use. These may be hardcoded values or references.
# variables: ## NOTHING AT THE MOMENT ##

# Specify to trigger this CI pipeline whenever changes are pushed to the master branch. TODO: Make 'release' version later!
trigger: 
- master

# Specify triggers for pull-requests. I don't want this to occur at this point in time.
pr: 
- none

variables:
# Web app name
  webAppName: 'igortcc'

  # Environment name
  environmentName: 'igortcc'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

# Define the 'stages' of this pipeline. A stage is a high level 'operation' that form the biggest building blocks
# of a pipeline, and are usually conducted sequentially.
stages:
- stage: buildReactApp  # name of the stage
  displayName: Build and bundle React app with 'npm run-script build'  # name to display in the UI
  dependsOn: [] # Specifies stages (by name) which this stage must run AFTER. Controls parallelism of stage operation
  jobs:
  - job: create_react_app_build
    displayName: create-react-app build
    continueOnError: false
    pool:
      vmImage: 'ubuntu-latest'
    workspace:
      clean: outputs
    steps:
    - bash: npm install
      workingDirectory: ClientApp
    # Execute the 'npm run-script build' command in the React-app directory
    - bash: npm run-script build
      workingDirectory: ClientApp
    # The previous command will have generated a 'build' folder which contains the compiled, deployable react-app content.
    # In order for our subsequent deployment stage to access this, we must use the 'publish' step. This publishes a "pipeline artifact"
    # So that it can be accessed later. We will use this to later access the build directory and publish it to the
    # appropriate $web blob container acting as our static web-server for the React Application.
    - publish: ClientApp/build
      # provide a name for this artifact
      artifact: reactAppBuild

- stage: deployReactApp
  displayName: Deploy reactApp build artifacts to Azure Storage
  dependsOn: [buildReactApp]
  jobs:
  - job: deployReactApp
    displayName: Download React build Artifact and copy to Azure Storage
    continueOnError: false
    pool:
      vmImage: $(vmImageName)   # We must use Windows agents for this job, because the Azure File Copy task only supports windows atm :(
    workspace:
      clean: outputs
    
# This stage will run a 'dotnet build' command, to ensure the project can build successfully. If it passes, we will
# deploy to kudu using the kudu rest API, in a later stage.
- stage: buildDotNetCoreApp
  displayName: Build the backend api
  dependsOn: [] # Can run in parallel with React App deployment, since they are independent applications 
  jobs:
  - job: dotnetbuild
    displayName: dotnet build job
    continueOnError: false  # fail the pipeline if this step fails
    pool:
      vmImage: $(vmImageName)
    workspace:
      clean: outputs
    steps:
    # Use the DotNetCoreCLI@2 built-in task to perform a simple build
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'

# This stages uses kudu rest API commands to explicitly deploy the api app to Azure app-service. This only runs
# if the .net-core build stage passed, to make sure we don't deploy broken code. 
# once the initial publish completes, we remotely run 'dotnet ef database update' to ensure EF-Migrations are applied
# to our Azure SQL Database. This command can be executed on the target machine using the /api/command Kudu REST Api
# endpoint
- stage: Deploy
  displayName: Deploy stage
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            displayName: 'Azure App Service Deploy: igortcc'
            inputs:
              azureSubscription: '357205d7-4c6d-4aae-8cc6-80df62be6d4c'
              appType: webAppLinux
              WebAppName: $(webAppName)
              packageForLinux: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              RuntimeStack: 'NODE|10.10'
              StartupCommand: 'npm run start'
              ScriptType: 'Inline Script'
              InlineScript: |
                npm install
                npm run build --if-present