# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy

version: 0.2

env:
    variables:
        PROJECT: tcc

phases:
    install:
        commands:
            - echo Install started on `date`
            - apt-get update -y
            - apt-get install -y dotnet6
            - sudo apt-get install curl
            - curl -sL https://deb.nodesource.com/setup_current.x | sudo -E bash –
            - sudo apt-get install -y nodejs
            - node -v
            
    pre_build:
        commands:
            - echo Restore started on `date`
            - dotnet restore
            - npm install
      
    build:
        commands:
            - echo Build started on `date`
            - dotnet build -c Release
            - dotnet test -c Release --logger trx --results-directory ./testresults
      
    post_build:
        commands:
            - echo Publish started on `date`
            - ls
            - ls -la
            - dotnet publish -c Release  -r ubuntu-x64 -o ./build_output ./${PROJECT}.csproj --self-contained false

artifacts:
    files:
        - '**/*'
    base-directory: ./build_output
    discard-paths: no
